# SETUP YAML file for Machine Vision Example - December 2019

EVA:
  comm:
#    host: "192.168.0.100"
#    token: "1cd9853842b26eae921b297c29eb33735639f4a2"
    host: "http://office.automata.tech:4242"
    token: "d3ebc4d086afca85560b6c8a2ac969750b3ad1b7"
  end_effector:
    payload: 0        # payload [kg]
    length: 88        # length of tool [mm]
    offset:           # ee offset in ee-frame  [m]
      - 0
      - 0
      - 0
  hover_height: 0.1   # elevation of idle z axis wrt to the object [m]
  work_radius: 0.6    # Eva's workspace radius [m]
  base_plate: 0.132   # Eva's base-plate dimension [m]

grids:
  names:
    - 'A'
    - 'B'
  names_verbose:  # object names
    A: 'Origin'
    B: 'Target'
  counter:        # initial object counter
    A: 0
    B: 0
  row:            # grid rows, [#]
    A: 2
    B: 3
  col:            # grid cols, [#]
    A: 2
    B: 3
  row_pitch:      # rows pitch [mm]
    A: 20
    B: 20
  col_pitch:      # cols pitch [mm]
    A: 30
    B: 30
  x0:             # grid angle, x [mm]
    A: 400
    B: 400
  y0:             # grid angle, y [mm]
    A: 100
    B: -60
  angle:          # grid orientation, [deg]
    A: 0
    B: 0
  angle_pickup:   # additional pick-up angle, [deg]
    A: 0
    B: 0
  surface:        # surf height of grid, [mm]
    A: 30
    B: 70
  object:         # object height, [mm]
    A: 0
    B: 0
  guess:
    A:            # joints grid guess, pick-up
      - 0
      - -0.97738438
      - -1.71042267
      - 0
      - -0.43633231
      - 0
    B:            # joints guess, drop-off
      - 0
      - -0.97738438
      - -1.71042267
      - 0
      - -0.43633231
      - 0

joints:
  home:        # joints for home position [rad]
    - -0.47919187
    - 0.9895437
    - -2.63661
    - -0.012847481
    - -1.3178256
    - -0.2752621
  mid_drop:
    - -0.9324012
    - -1.0720936
    - -1.2877203
    - -0.0071907546
    - -0.7813953
    - 0