# SETUP YAML file for Grid-to-grid demo - February 2020

EVA:
  work_radius: 0.6    # Eva's workspace radius [m] - DO NOT CHANGE THIS PARAMETER
  base_plate: 0.132   # Eva's base-plate dimension [m] - DO NOT CHANGE THIS PARAMETER
  comm:
#    host: "0.0.0.0"
#    token: "abcd1234"
    host: "http://office.automata.tech:4242" # USER DEFINED
    token: "d3ebc4d086afca85560b6c8a2ac969750b3ad1b7" # USER DEFINED
  end_effector:
    payload: 0        # payload [kg] - USER DEFINED
    length: 88        # length of tool [mm] - USER DEFINED
    offset:           # ee offset in ee-frame  [m] - USER DEFINED
      - 0
      - 0
      - 0
  hover_height: 0.1   # elevation of idle z axis wrt to the object [m] - USER DEFINED
  home:               # joints for home position [rad] - USER DEFINED
    - 0
    - 0
    - 0
    - 0
    - 0
    - 0

grids:
  names:          # DO NOT CHANGE THIS PARAMETER
    - 'A'
    - 'B'
  names_verbose:  # object names - USER DEFINED
    A: 'Origin'
    B: 'Target'
  row:            # grid rows, [#] - USER DEFINED
    A: 4
    B: 3
  col:            # grid cols, [#] - USER DEFINED
    A: 3
    B: 4
  row_pitch:      # rows pitch [mm] - USER DEFINED
    A: 50
    B: 80
  col_pitch:      # cols pitch [mm] - USER DEFINED
    A: 80
    B: 80
  x0:             # grid angle, x [mm] - USER DEFINED
    A: 350
    B: -100
  y0:             # grid angle, y [mm] - USER DEFINED
    A:  200
    B: -350
  angle:          # grid orientation, [deg] - USER DEFINED
    A: 30
    B: -90
  angle_pickup:   # additional pick-up angle, [deg] - USER DEFINED
    A: 0
    B: 0
  surface:        # surf height of grid, [mm] - USER DEFINED
    A: 40
    B: 150
  object:         # object height, [mm] - USER DEFINED
    A: 0
    B: 0
  guess:
    A:            # joints grid guess, pick-up [rad] - USER DEFINED
      - 0
      - -0.97738438
      - -1.71042267
      - 0
      - -0.43633231
      - 0
    B:            # joints guess, drop-off [rad] - USER DEFINED
      - -1.4
      - -0.97738438
      - -1.71042267
      - 0
      - -0.43633231
      - 0